name: luanvan
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.6
  flutter_local_notifications: ^17.2.3
  loading_animation_widget: ^1.2.0
  web_socket_channel: ^3.0.1
  debounce_throttle: ^2.0.0
  intl: ^0.19.0
  translator: ^1.0.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  path_provider: ^2.0.0
  firebase_storage: ^12.4.6
  connectivity_plus: ^5.0.2
  file_picker: ^10.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/gg.png
    - assets/face.png
    - assets/X.jpg
    - assets/img.png
    - assets/credentials.json  # ThÃªm file credentials.json
  fonts:
    - family: Tahoma
      fonts:
        - asset: assets/fonts/Tahoma.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/Arial.ttf